security:
    encoders:
         App\Entity\User: bcrypt
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
             anonymous: ~
             logout:
                 path: security_logout
             guard:
                 authenticators:
                        - App\Security\LoginFormAuthenticator
    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/products, roles: [ROLE_USER, ROLE_ADMIN] }