security:
    encoders:
            # use your user class name here
        App\Entity\User:
            # bcrypt or argon2i are recommended
            # argon2i is more secure, but requires PHP 7.2 or the Sodium extension
            algorithm: bcrypt
            cost: 12
    providers:
      in_memory: { memory: ~ }
#      in_memory:
#        memory:
#          users:
#            halyna:
#              password: qwerty
#              roles: 'ROLE_USER'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true


    access_control:
#         - { path: ^/login, roles: ROLE_USER }
#         - { path: ^/register, roles: ROLE_USER }
