security:
    encoders:
         App\Entity\User: bcrypt
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
             anonymous: ~
             logout:
                 path: security_logout
             guard:
                 authenticators:
                       - App\Security\GoogleAuthenticator
                       #- App\Security\OAuthAuthenticator
    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/products, roles: [ROLE_USER, ROLE_ADMIN] }

knpu_oauth2_client:
    clients:
        google:
            # must be "google" - it activates that type!
            type: google
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
            client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_google_check
            redirect_params: {}
